General:
  'cleanColumnsThresold': 0.3
  'resample': 'h'                    # at least 'h' if we want to merge weather data

Forecasting:
  'stepsIn': 504          # 21 days = 3 weeks
  'stepsOut': 168         #  7 days = 1 week
  'verbose': 0            # GridSearchCV is parallelized and prints are highly inconsistant
  LSTM:
    'GridSearchCV': {
        'epochs': [5, 10],
        'L2': [0, 0.1, 0.3],
        'alpha': [0.01, 0.1, 0.3],
        'batch_size': [64, 128],
        'dropout': [0.1, 0.3, 0.5],
        'learning_rate': [0.001, 0.01],
        'optimizer': ['adam']
      }
  SARIMAX:
    GridSearchCV: {
      p: [0, 1, 2, 3],
      d: [0,1,2],
      q: [0, 1, 2, 3],
      P: [0, 1, 2, 3],
      D: [0, 1, 2],
      Q: [0, 1, 2, 3],
      s: [24]}
