Optimal LSTM Parameters:
  L2: 0
  alpha: 0.1
  batch_size: 128
  dropout: 0.3
  epochs: 10
  learning_rate: 0.01
  optimizer: adam
Optimal SARIMAX Parameters:
  p: 3
  d: 0
  q: 3
  P: 1
  D: 1
  Q: 1
  s: 24
