# config.yaml

General:
  'input': '../data/routes.csv'
  'enrichment': '../data/lima_2015_weatherdata.csv'
  'cleanColumnsThresold': 0.3
  'imputation': 'KNN'                # 'KNN'/'MICE' in case -i is given
  'resample': 'h'                    # at least 'h' if we want to merge weather data

Forecasting:
  'stepsOut': 12
  'stepsIn': 72
  'testSize': 0.2
  LSTM:
    'GridSearchCV': {
        'epochs': [5, 10, 20],
        'L2': [0.1, 0.001, 0.001],
        'batchSize': [16, 32, 64, 128],
        'dropout': [0.1, 0.3, 0.5],
        'learningRate': [0.001, 0.005, 0.01, 0.015]
      }
