# config.yaml

General:
  'input': '../data/routes.csv'
  'enrichment': '../data/lima_2015_weatherdata.csv'
  'cleanColumnsThresold': 0.3
  'imputation': 'KNN'                # 'KNN'/'MICE' in case -i is given
  'resample': 'h'                    # at least 'h' if we want to merge weather data

Forecasting:
  'stepsIn': 504          # 21 days = 3 weeks
  'stepsOut': 168         #  7 days = 1 week
  'verbose': 0                       # GridSearchCV is parallelized and prints are highly inconsistant
  LSTM:
    'GridSearchCV': {
        'epochs': [5, 10],
        'L2': [0, 0.1, 0.01],
        'batchSize': [32, 128],
        'dropout': [0, 0.3],
        'learningRate': [0.001, 0.01],
        'optimizer': ['adam']
      }
  SARIMAX:
    GridSearchCV: {
      p: [0, 1, 2, 3],
      d: [0,1,2],
      q:[0, 1, 2, 3],
      P: [0, 1, 2, 3],
      D: [0, 1, 2],
      Q: [0, 1, 2, 3],
      s: [24]}
Optimal LSTM Parameters:
  L2: 0
  batchSize: 32
  dropout: 0.3
  epochs: 10
  learningRate: 0.01
  optimizer: RMSprop
Optimal SARIMAX Parameters:
  p: 1
  d: 0
  q: 1
  P: 1
  D: 1
  Q: 1
  s: 24
