# config.yaml

General:
  'input': '../data/routes.csv'
  'enrichment': '../data/lima_2015_weatherdata.csv'
  'cleanColumnsThresold': 0.3
  'imputation': 'KNN'                # 'KNN'/'MICE' in case -i is given
  'resample': 'h'                    # at least 'h' if we want to merge weather data

Forecasting:
  'stepsOut': 504       # 21 days = 3 weeks
  'stepsIn': 125         # 7 days = 1 week
  'testSize': 0.2
  'verbose': 0                       # GridSearchCV is parallelized and prints are highly inconsistant
  LSTM:
    'GridSearchCV': {
        'epochs': [5],
        'L2': [0, 0.1],
        'batchSize': [32, 128],
        'dropout': [0, 0.3],
        'learningRate': [0.001, 0.01],
        'optimizer': ['adam']
      }
Optimal Parameters:
  L2: 0
  batchSize: 32
  dropout: 0.3
  epochs: 5
  learningRate: 0.001
  optimizer: adam
